spring.application.name=freelance-skill-analyzer

spring.datasource.url=jdbc:postgresql://localhost:5432/freelance_db
spring.datasource.username=yumitakeisi
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false